apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 2
  template:
    metadata: 
      name: webapp
      labels:
        app: webapp
    spec: 
      containers:
      - name: webapp
        image: tomcat
        ports: 
        - containerPort: 8080
