apiVersion: batch/v1alpha1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
     template:
       spec:
         containers:
         - name: hello
           image: buxybox
           args:
           - /bin/sh
           - -c
           - date; echo Hello from teh Kubernetes cluster
         restartPolicy: OnFailure
