apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: redis
    volumeMounts:
     - name: foo
       mountPath: "/etc/foo"
  volumes:
    - name: foo
      secret:
       secretName: mysecret
