apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-2
#  namespace: small
spec:
  capacity:
     storage: 1Gi
  accessModes:
     - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/test
    server: master1
    readOnly: false
